name: dactor
description: An actor system for Dart
version: 1.1.0
repository: https://github.com/stephanfeb/dactor

environment:
  sdk: ^3.5.1


# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  cbor: ^6.3.5
  meta: ^1.16.0
  uuid: ^4.4.0
  test: ^1.24.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  benchmark_harness: ^2.2.0
